# Generated by Django 2.0.7 on 2018-07-11 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='vore',
            new_name='vote',
        ),
    ]
